In [ ]:
#This program uses various libraries and machine learning techniques in order to analyze various text to detect fake news.

In [1]:
import pandas as pd #import pandas library
import numpy as np #import numpy library

In [2]:
workingDirectory = "C:/Users/Aja58/OneDrive/Documents/BTicketAnalysis/" #locating excel file from directory
inputDirectory = workingDirectory + "input/" #create an input directory
outputDirectory = workingDirectory + "output/" #create an output directory

commentsFilepath = inputDirectory + "news.xlsx" #Create a new filepath for comments

In [ ]:
#First, we read from our Excel file and put the data into a dataframe. 

In [3]:
df = pd.concat(pd.read_excel(commentsFilepath, sheet_name = None), ignore_index = False)#calling upon news excel file
df.shape #gives us our array
df.head() #returns first five rows of the excel news file

Unnamed: 0                                              title  \
news 0       8476                     You Can Smell Hillary’s Fear   
     1      10294  Watch The Exact Moment Paul Ryan Committed Pol...   
     2       3608        Kerry to go to Paris in gesture of sympathy   
     3      10142  Bernie supporters on Twitter erupt in anger ag...   
     4        875   The Battle of New York: Why This Primary Matters   

                                                     text label Unnamed: 4  \
news 0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE        NaN   
     1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE        NaN   
     2  U.S. Secretary of State John F. Kerry said Mon...  REAL        NaN   
     3  — Kaydee King (@KaydeeKing) November 9, 2016...  FAKE        NaN   
     4  It's primary day in New York and front-runners...  REAL        NaN   

       Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
news 0        NaN        NaN        NaN        NaN        NaN  ...   
     1        NaN        NaN        NaN        NaN        NaN  ...   
     2        NaN        NaN        NaN        NaN        NaN  ...   
     3        NaN        NaN        NaN        NaN        NaN  ...   
     4        NaN        NaN        NaN        NaN        NaN  ...   

       Unnamed: 131 Unnamed: 132 Unnamed: 133 Unnamed: 134 Unnamed: 135  \
news 0          NaN          NaN          NaN          NaN          NaN   
     1          NaN          NaN          NaN          NaN          NaN   
     2          NaN          NaN          NaN          NaN          NaN   
     3          NaN          NaN          NaN          NaN          NaN   
     4          NaN          NaN          NaN          NaN          NaN   

       Unnamed: 136 Unnamed: 137 Unnamed: 138 Unnamed: 139 Unnamed: 140  
news 0          NaN          NaN          NaN          NaN          NaN  
     1          NaN          NaN          NaN          NaN          NaN  
     2          NaN          NaN          NaN          NaN          NaN  
     3          NaN          NaN          NaN          NaN          NaN  
     4          NaN          NaN          NaN          NaN          NaN  

[5 rows x 141 columns]

In [4]:
#the only data we really need are the "title" and "text" columns.

df1 = df[['title', 'text']]#keeping the aforementioned columns and dropping the rest, creates new dataframe.
df1.shape #array
df1 

title  \
news 0                        You Can Smell Hillary’s Fear   
     1     Watch The Exact Moment Paul Ryan Committed Pol...   
     2           Kerry to go to Paris in gesture of sympathy   
     3     Bernie supporters on Twitter erupt in anger ag...   
     4      The Battle of New York: Why This Primary Matters   
...                                                      ...   
     7813  State Department says it can't find emails fro...   
     7814  The ‘P’ in PBS Should Stand for ‘Plutocr...   
     7815  Anti-Trump Protesters Are Tools of the Oligarc...   
     7816  In Ethiopia, Obama seeks progress on peace, se...   
     7817  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                        text  
news 0     Daniel Greenfield, a Shillman Journalism Fello...  
     1     Google Pinterest Digg Linkedin Reddit Stumbleu...  
     2     U.S. Secretary of State John F. Kerry said Mon...  
     3     — Kaydee King (@KaydeeKing) November 9, 2016...  
     4     It's primary day in New York and front-runners...  
...                                                      ...  
     7813  The State Department told the Republican Natio...  
     7814  The ‘P’ in PBS Should Stand for ‘Plutocr...  
     7815   Anti-Trump Protesters Are Tools of the Oligar...  
     7816  ADDIS ABABA, Ethiopia —President Obama conve...  
     7817  Jeb Bush Is Suddenly Attacking Trump. Here's W...  

[7818 rows x 2 columns]

In [ ]:
#we will now import functions from our sklearn library.

In [5]:
from sklearn.pipeline import Pipeline #importing Pipeline from sklearn library, making our data easier to read.
from sklearn.pipeline import make_pipeline #construct pipeline

from sklearn.impute import SimpleImputer #fills in any missing data
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier #looks for the five nearest neighbors
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


In [ ]:
#start training the model

In [10]:
from mlxtend.feature_selection import ColumnSelector #will be used when we select column to work off of
from sklearn.feature_extraction.text import TfidfVectorizer #counts as CountVectorizer and TfidfVectorizer
#from sklearn.feature_extraction.text import CountVectorizer
from sklearn.compose import ColumnTransformer

pipe = Pipeline([ #create our pipeline
    ('vect', TfidfVectorizer()), #will transform text into vector, given frequency of the word
    ('clf', LogisticRegression())
])


df_Xtrain = pd.DataFrame({'text': ['REAL']*10,
                         'label': 0})
y_train = df_Xtrain['label'].to_numpy().ravel()


pipe = Pipeline([
    ('col_selector', ColumnSelector(cols=('text'),drop_axis=True)),
      ('tfidf', TfidfVectorizer()),
    ('kMeans', KNeighborsClassifier()),
])


pipe.fit(df_Xtrain,y_train)

Pipeline(steps=[('col_selector', ColumnSelector(cols='text', drop_axis=True)),
                ('tfidf', TfidfVectorizer()),
                ('kMeans', KNeighborsClassifier())])

In [11]:
text = Pipeline(steps=[('col_selector', ColumnSelector(cols='text', drop_axis=True)),
                 ('tfidf', TfidfVectorizer()), ('kMeans', KNeighborsClassifier())])

kMeansModel = text.fit(df_Xtrain,y_train)
print(kMeansModel)
print(kMeansModel.score(df_Xtrain,y_train))

Pipeline(steps=[('col_selector', ColumnSelector(cols='text', drop_axis=True)),
                ('tfidf', TfidfVectorizer()),
                ('kMeans', KNeighborsClassifier())])
1.0


In [ ]:
#Using tfidfvectorizer, we get a 1.0 which means our text data is good.

In [ ]:
#now train model for"title" column

In [14]:
df_Xtrain2 = pd.DataFrame({'title': ['REAL']*10,
                          'label': 0})
y_train2 = df_Xtrain['label'].to_numpy().ravel()

pipe = Pipeline([
    ('col_selector', ColumnSelector(cols=('title'),drop_axis=True)),
    ('tfidf', TfidfVectorizer()), #uses both a count vectorizer and tfidf transformer
    ('kMeans', KNeighborsClassifier()),
])


pipe.fit(df_Xtrain2,y_train2)

Pipeline(steps=[('col_selector', ColumnSelector(cols='title', drop_axis=True)),
                ('tfidf', TfidfVectorizer()),
                ('kMeans', KNeighborsClassifier())])

In [13]:
title = Pipeline(steps=[('col_selector', ColumnSelector(cols='title', drop_axis=True)),
                 ('tfidf', TfidfVectorizer()), ('kMeans', KNeighborsClassifier())])

kMeansModel = title.fit(df_Xtrain2,y_train2)
print(kMeansModel)
print(kMeansModel.score(df_Xtrain2,y_train2))

Pipeline(steps=[('col_selector', ColumnSelector(cols='title', drop_axis=True)),
                ('tfidf', TfidfVectorizer()),
                ('kMeans', KNeighborsClassifier())])
1.0


In [ ]:
#Likewise, using tfidfvectorizer, we received a 1.0 which means our data for the "title" column is good.

In [15]:
df1_count = df1.text.str.split(expand=True).stack().value_counts().reset_index()#Word Count of words in text column before pre-processing

df1_count.columns = ['Word', 'Frequency']

df1_count

Word  Frequency
0                the     254545
1                 to     134936
2                 of     126506
3                and     109829
4                  a     101219
...              ...        ...
218148         fix,"          1
218149       quarks,          1
218150          92-8          1
218151  antineutron,          1
218152      script."          1

[218153 rows x 2 columns]

In [16]:
df1_count = df1.title.str.split(expand=True).stack().value_counts().reset_index()#Word Count of words in title column before pre-processing

df1_count.columns = ['Word', 'Frequency']

df1_count

Word  Frequency
0           the       1900
1            to       1614
2            of       1215
3            in       1070
4           The        954
...         ...        ...
20469  Confound          1
20470       (At          1
20471     Some)          1
20472      cock          1
20473  Suddenly          1

[20474 rows x 2 columns]

In [ ]:
#we have a lot of "stopwords", such as "the", "to" "of", etc. in both our text and title columns, which provide little to no valuable information to the model. Similarly, converting all characters to lowercase will allow us to achieve more helpful data.

In [17]:
#TEXT PREPROCESSING PORTION
#Start by making all characters in our "text" and "title" columns lowercase.

df1['text'] = df1['text'].str.lower()
df1['title'] = df1['title'].str.lower()

C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\1080283383.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['text'] = df1['text'].str.lower()
C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\1080283383.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['title'] = df1['title'].str.lower()#makes everything in text and title column lowercase


In [18]:
#We will now remove all non-alphanumeric characters. Certain characters and symbols provide very little valuable information to the model.

df1['text'] = df1.text.str.replace('[^0-9a-zA-Z ]+' , '')
df1['title'] = df1.title.str.replace('[^0-9a-zA-Z ]+' , '')

df1

C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\2165309834.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['text'] = df1.text.str.replace('[^0-9a-zA-Z ]+' , '')
C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\2165309834.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['text'] = df1.text.str.replace('[^0-9a-zA-Z ]+' , '')
C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\2165309834.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df1['title'] = df1.title.str.replace('[^0-9a-zA-Z ]+' , '')
C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\2165309834.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from

title  \
news 0                           you can smell hillarys fear   
     1     watch the exact moment paul ryan committed pol...   
     2           kerry to go to paris in gesture of sympathy   
     3     bernie supporters on twitter erupt in anger ag...   
     4       the battle of new york why this primary matters   
...                                                      ...   
     7813  state department says it cant find emails from...   
     7814  the p in pbs should stand for plutocratic or p...   
     7815  antitrump protesters are tools of the oligarch...   
     7816  in ethiopia obama seeks progress on peace secu...   
     7817  jeb bush is suddenly attacking trump heres why...   

                                                        text  
news 0     daniel greenfield a shillman journalism fellow...  
     1     google pinterest digg linkedin reddit stumbleu...  
     2     us secretary of state john f kerry said monday...  
     3      kaydee king kaydeeking november 9 2016 the le...  
     4     its primary day in new york and frontrunners h...  
...                                                      ...  
     7813  the state department told the republican natio...  
     7814  the p in pbs should stand for plutocratic or p...  
     7815   antitrump protesters are tools of the oligarc...  
     7816  addis ababa ethiopia president obama convened ...  
     7817  jeb bush is suddenly attacking trump heres why...  

[7818 rows x 2 columns]

In [ ]:
#We will now import a list of stopwords from the nltk library. Stopwords provide little to no valuable information to our model. It is best to remove them.

In [19]:
import nltk
import string
nltk.download('stopwords')
from nltk.corpus import stopwords#gives us our list of stopwords
" ".join(stopwords.words('english'))
stop_words = set(stopwords.words('english'))


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Aja58\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
stop_words#list of stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [21]:
def remove_stop(x):
    return " ".join([word for word in str(x).split() if word not in stop_words])#removes stopwords
df1['text'] = df1['text'].apply(lambda x : remove_stop(x))#applies the removal of stopwords to the text column

C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\3866130103.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['text'] = df1['text'].apply(lambda x : remove_stop(x))#applies the removal of stopwords


In [22]:
df1

title  \
news 0                           you can smell hillarys fear   
     1     watch the exact moment paul ryan committed pol...   
     2           kerry to go to paris in gesture of sympathy   
     3     bernie supporters on twitter erupt in anger ag...   
     4       the battle of new york why this primary matters   
...                                                      ...   
     7813  state department says it cant find emails from...   
     7814  the p in pbs should stand for plutocratic or p...   
     7815  antitrump protesters are tools of the oligarch...   
     7816  in ethiopia obama seeks progress on peace secu...   
     7817  jeb bush is suddenly attacking trump heres why...   

                                                        text  
news 0     daniel greenfield shillman journalism fellow f...  
     1     google pinterest digg linkedin reddit stumbleu...  
     2     us secretary state john f kerry said monday st...  
     3     kaydee king kaydeeking november 9 2016 lesson ...  
     4     primary day new york frontrunners hillary clin...  
...                                                      ...  
     7813  state department told republican national comm...  
     7814  p pbs stand plutocratic pentagon posted oct 27...  
     7815  antitrump protesters tools oligarchy reform al...  
     7816  addis ababa ethiopia president obama convened ...  
     7817  jeb bush suddenly attacking trump heres matter...  

[7818 rows x 2 columns]

In [23]:
df1['title'] = df1['title'].apply(lambda x : remove_stop(x))#removes stopwords in title column
df1

C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\1639901177.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['title'] = df1['title'].apply(lambda x : remove_stop(x))#removes stopwords in title column


title  \
news 0                                   smell hillarys fear   
     1     watch exact moment paul ryan committed politic...   
     2                       kerry go paris gesture sympathy   
     3     bernie supporters twitter erupt anger dnc trie...   
     4                       battle new york primary matters   
...                                                      ...   
     7813  state department says cant find emails clinton...   
     7814                   p pbs stand plutocratic pentagon   
     7815   antitrump protesters tools oligarchy information   
     7816  ethiopia obama seeks progress peace security e...   
     7817    jeb bush suddenly attacking trump heres matters   

                                                        text  
news 0     daniel greenfield shillman journalism fellow f...  
     1     google pinterest digg linkedin reddit stumbleu...  
     2     us secretary state john f kerry said monday st...  
     3     kaydee king kaydeeking november 9 2016 lesson ...  
     4     primary day new york frontrunners hillary clin...  
...                                                      ...  
     7813  state department told republican national comm...  
     7814  p pbs stand plutocratic pentagon posted oct 27...  
     7815  antitrump protesters tools oligarchy reform al...  
     7816  addis ababa ethiopia president obama convened ...  
     7817  jeb bush suddenly attacking trump heres matter...  

[7818 rows x 2 columns]

In [ ]:
#after the removal of stopwords, we will now check the words and frequency of a word in the text column.

In [24]:
df1_count = df1.text.str.split(expand=True).stack().value_counts().reset_index()

df1_count.columns = ['Word', 'Frequency']

df1_count

Word  Frequency
0                     said      18795
1                    trump      16691
2                  clinton      13285
3                    would      12426
4                       us      12016
...                    ...        ...
139536          watchtower          1
139537  defendantsdefining          1
139538     supportspeaking          1
139539           saidkhizr          1
139540            studious          1

[139541 rows x 2 columns]

In [ ]:
#since we removed the stopwords, we get less generic words such as "that", "the", "at", etc. that can be applied anywhere. Now we get more specific words that can be deemed important information.

In [25]:
#check word and frequency of the title column.

df1_count = df1.title.str.split(expand=True).stack().value_counts().reset_index()

df1_count.columns = ['Word', 'Frequency']

df1_count

Word  Frequency
0                      trump        943
1                        nan        637
2                    clinton        626
3                    hillary        526
4                         us        369
...                      ...        ...
11951  boycottcomedianrobert          1
11952                 feelin          1
11953                 deniro          1
11954              antarctic          1
11955            plutocratic          1

[11956 rows x 2 columns]

In [26]:
df1

title  \
news 0                                   smell hillarys fear   
     1     watch exact moment paul ryan committed politic...   
     2                       kerry go paris gesture sympathy   
     3     bernie supporters twitter erupt anger dnc trie...   
     4                       battle new york primary matters   
...                                                      ...   
     7813  state department says cant find emails clinton...   
     7814                   p pbs stand plutocratic pentagon   
     7815   antitrump protesters tools oligarchy information   
     7816  ethiopia obama seeks progress peace security e...   
     7817    jeb bush suddenly attacking trump heres matters   

                                                        text  
news 0     daniel greenfield shillman journalism fellow f...  
     1     google pinterest digg linkedin reddit stumbleu...  
     2     us secretary state john f kerry said monday st...  
     3     kaydee king kaydeeking november 9 2016 lesson ...  
     4     primary day new york frontrunners hillary clin...  
...                                                      ...  
     7813  state department told republican national comm...  
     7814  p pbs stand plutocratic pentagon posted oct 27...  
     7815  antitrump protesters tools oligarchy reform al...  
     7816  addis ababa ethiopia president obama convened ...  
     7817  jeb bush suddenly attacking trump heres matter...  

[7818 rows x 2 columns]

In [ ]:
#Now we want to start encoding to transform categorical values into numerical values. The machine can only work in numerical values!

In [27]:
#start by importing encoder oriented functions from sklearn library.

from sklearn.preprocessing import LabelEncoder #import more sklearn functions

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import OrdinalEncoder

In [28]:
labelencoder = LabelEncoder() #encodes our title column

df1['titles_encoded'] = labelencoder.fit_transform(df1['title'])

print(df1)
df1['titles_encoded'].value_counts()

                                                       title  \
news 0                                   smell hillarys fear   
     1     watch exact moment paul ryan committed politic...   
     2                       kerry go paris gesture sympathy   
     3     bernie supporters twitter erupt anger dnc trie...   
     4                       battle new york primary matters   
...                                                      ...   
     7813  state department says cant find emails clinton...   
     7814                   p pbs stand plutocratic pentagon   
     7815   antitrump protesters tools oligarchy information   
     7816  ethiopia obama seeks progress peace security e...   
     7817    jeb bush suddenly attacking trump heres matters   

                                                        text  titles_encoded  
news 0     daniel greenfield shillman journalism fellow f...            5651  
     1     google pinterest digg linkedin reddit stumbleu...            6

C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\590820929.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['titles_encoded'] = labelencoder.fit_transform(df1['title'])


4084    637
0        14
2184      5
4543      5
5064      5
       ... 
1930      1
4510      1
2578      1
5164      1
3359      1
Name: titles_encoded, Length: 7031, dtype: int64

In [29]:
labelencoder = LabelEncoder()

df1['text_encoded'] = labelencoder.fit_transform(df1['text'])

print(df1)
df1['text_encoded'].value_counts()#encodes our text column

                                                       title  \
news 0                                   smell hillarys fear   
     1     watch exact moment paul ryan committed politic...   
     2                       kerry go paris gesture sympathy   
     3     bernie supporters twitter erupt anger dnc trie...   
     4                       battle new york primary matters   
...                                                      ...   
     7813  state department says cant find emails clinton...   
     7814                   p pbs stand plutocratic pentagon   
     7815   antitrump protesters tools oligarchy information   
     7816  ethiopia obama seeks progress peace security e...   
     7817    jeb bush suddenly attacking trump heres matters   

                                                        text  titles_encoded  \
news 0     daniel greenfield shillman journalism fellow f...            5651   
     1     google pinterest digg linkedin reddit stumbleu...           

C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\1272914007.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['text_encoded'] = labelencoder.fit_transform(df1['text'])


3582    893
3054     58
0        39
6033     23
1680     17
       ... 
827       1
5046      1
3966      1
2974      1
2931      1
Name: text_encoded, Length: 6634, dtype: int64

In [ ]:
#After encoding our "text" and "title" columns, the machine now has its information in numerical values. We now must use an imputer to fill in missing values (NAN) in the dataset.

In [30]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')#replaces NAN values with most frequent values

df1[['text', 'title']] = imputer.fit_transform(df1[['text_encoded', 'titles_encoded']])#applying the imputer to the select columns
print(df1.head())

        title  text  titles_encoded  text_encoded
news 0   5651  1249            5651          1249
     1   6758  2294            6758          2294
     2   3482  6001            3482          6001
     3    634  3037             634          3037
     4    559  4518             559          4518


C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\2507572102.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['text', 'title']] = imputer.fit_transform(df1[['text_encoded', 'titles_encoded']])#applying the imputer to the select columns


In [ ]:
#We will now try encoding using the "OneHotEncoder" function, which will take numerical features into "dummy" features.

In [31]:
from sklearn.preprocessing import OneHotEncoder#will make categories of the values in the targetnames column

oHE = OneHotEncoder()

transformed = oHE.fit_transform(df1['text_encoded'].to_numpy().reshape(-1,1))

print(transformed.toarray()[:10])
print(oHE.categories_)
print(df1.head())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[array([   0,    1,    2, ..., 6631, 6632, 6633])]
        title  text  titles_encoded  text_encoded
news 0   5651  1249            5651          1249
     1   6758  2294            6758          2294
     2   3482  6001            3482          6001
     3    634  3037             634          3037
     4    559  4518             559          4518


In [ ]:
#Using the OneHotEncoder function resulted in a lot of 0s. This could be do to a significant amount of stopwords in the original "text" and "title" columns.

In [32]:
train_x = pd.get_dummies(df1, columns =['text_encoded'])#gives us 1's and 0's which will tell us if it matches with the column header
print(train_x.shape)
print(train_x.columns)
print(train_x.head())

(7818, 6637)
Index(['title', 'text', 'titles_encoded', 'text_encoded_0', 'text_encoded_1',
       'text_encoded_2', 'text_encoded_3', 'text_encoded_4', 'text_encoded_5',
       'text_encoded_6',
       ...
       'text_encoded_6624', 'text_encoded_6625', 'text_encoded_6626',
       'text_encoded_6627', 'text_encoded_6628', 'text_encoded_6629',
       'text_encoded_6630', 'text_encoded_6631', 'text_encoded_6632',
       'text_encoded_6633'],
      dtype='object', length=6637)
        title  text  titles_encoded  text_encoded_0  text_encoded_1  \
news 0   5651  1249            5651               0               0   
     1   6758  2294            6758               0               0   
     2   3482  6001            3482               0               0   
     3    634  3037             634               0               0   
     4    559  4518             559               0               0   

        text_encoded_2  text_encoded_3  text_encoded_4  text_encoded_5  \
news 0             

In [33]:
train_x = pd.get_dummies(df1, columns =['titles_encoded'])#gives us 1's and 0's which will tell us if it matches with the column header
print(train_x.shape)
print(train_x.columns)
print(train_x.head())

(7818, 7034)
Index(['title', 'text', 'text_encoded', 'titles_encoded_0', 'titles_encoded_1',
       'titles_encoded_2', 'titles_encoded_3', 'titles_encoded_4',
       'titles_encoded_5', 'titles_encoded_6',
       ...
       'titles_encoded_7021', 'titles_encoded_7022', 'titles_encoded_7023',
       'titles_encoded_7024', 'titles_encoded_7025', 'titles_encoded_7026',
       'titles_encoded_7027', 'titles_encoded_7028', 'titles_encoded_7029',
       'titles_encoded_7030'],
      dtype='object', length=7034)
        title  text  text_encoded  titles_encoded_0  titles_encoded_1  \
news 0   5651  1249          1249                 0                 0   
     1   6758  2294          2294                 0                 0   
     2   3482  6001          6001                 0                 0   
     3    634  3037          3037                 0                 0   
     4    559  4518          4518                 0                 0   

        titles_encoded_2  titles_encoded_3  title

In [34]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')#replaces NAN values with most frequent values

df1[['text', 'title']] = imputer.fit_transform(df1[['text_encoded', 'titles_encoded']])#applying the imputer to the select columns
print(df1.head())

        title  text  titles_encoded  text_encoded
news 0   5651  1249            5651          1249
     1   6758  2294            6758          2294
     2   3482  6001            3482          6001
     3    634  3037             634          3037
     4    559  4518             559          4518


C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\2507572102.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['text', 'title']] = imputer.fit_transform(df1[['text_encoded', 'titles_encoded']])#applying the imputer to the select columns


In [35]:
#standardize the data 

standardScaler = StandardScaler()#applying the scaling. measures standard deviation of the values

columnsToTransform = ['text_encoded', 'titles_encoded']

df1[columnsToTransform] = standardScaler.fit_transform(df1[columnsToTransform])
print(df1.head())

        title  text  titles_encoded  text_encoded
news 0   5651  1249        1.073235     -1.152734
     1   6758  2294        1.639662     -0.574249
     2   3482  6001       -0.036594      1.477849
     3    634  3037       -1.493851     -0.162944
     4    559  4518       -1.532227      0.656899


C:\Users\Aja58\AppData\Local\Temp\ipykernel_6148\987694671.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[columnsToTransform] = standardScaler.fit_transform(df1[columnsToTransform])


In [ ]:
#Now we must check the mean and standard deviation of the dat after standardizing.

In [39]:
np.mean(df1[columnsToTransform], axis = 0)

text_encoded     -6.191574e-17
titles_encoded   -1.483688e-16
dtype: float64

In [ ]:
#The mean of both the encoded title column and encoded text column are very close to 0.

In [40]:
np.std(df1[columnsToTransform], axis = 0)

text_encoded      1.0
titles_encoded    1.0
dtype: float64

In [ ]:
#Our standard deviation of both the encoded text column and encoded title column are 1.

In [36]:
from sklearn.preprocessing import OneHotEncoder#will make categories of the values in the targetnames column

oHE = OneHotEncoder()

transformed = oHE.fit_transform(df1['text_encoded'].to_numpy().reshape(-1,1))

print(transformed.toarray()[:10])
print(oHE.categories_)
print(df1.head())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[array([-1.84414742, -1.84359385, -1.84304027, ...,  1.82660031,
        1.82715388,  1.82770746])]
        title  text  titles_encoded  text_encoded
news 0   5651  1249        1.073235     -1.152734
     1   6758  2294        1.639662     -0.574249
     2   3482  6001       -0.036594      1.477849
     3    634  3037       -1.493851     -0.162944
     4    559  4518       -1.532227      0.656899


In [37]:
train_x = pd.get_dummies(df1, columns =['text_encoded', 'titles_encoded'])#gives us 1's and 0's which will tell us if it matches with the column header
print(train_x.shape)
print(train_x.columns)
print(train_x.head())

(7818, 13667)
Index(['title', 'text', 'text_encoded_-1.8441474219311518',
       'text_encoded_-1.8435938481518628', 'text_encoded_-1.843040274372574',
       'text_encoded_-1.842486700593285', 'text_encoded_-1.841933126813996',
       'text_encoded_-1.841379553034707', 'text_encoded_-1.8408259792554182',
       'text_encoded_-1.8402724054761292',
       ...
       'titles_encoded_1.7742333879189238',
       'titles_encoded_1.7747450655042567',
       'titles_encoded_1.7752567430895894',
       'titles_encoded_1.7757684206749222', 'titles_encoded_1.776280098260255',
       'titles_encoded_1.7767917758455878',
       'titles_encoded_1.7773034534309204',
       'titles_encoded_1.7778151310162533', 'titles_encoded_1.778326808601586',
       'titles_encoded_1.7788384861869189'],
      dtype='object', length=13667)
        title  text  text_encoded_-1.8441474219311518  \
news 0   5651  1249                                 0   
     1   6758  2294                                 0   
     2 

In [ ]:
#Even using get_dummies, we still get 0's. This might be a result of the original title and text columns having an excess of stopwords.